### PR TITLE
issues 31 and 32

### PR DESCRIPTION
**Pull request by jettlin**
Fixes issues #31 and #32 by doing the following:

- Adds a confirm dialog when clicking the delete button
- Does not show the delete button if you select all items UNLESS you only have 1 video
- Fixed issue with usernames not displaying (caused by an issue with indices)

### CODE REVIEW

**Comment by jettlin** [comment]
Adding in a font family fix for #35

**Comment by jettlin** [comment]
Adding description fix for #36

**Comment by jettlin** [comment]
Addressing #34

**Comment by jettlin** [comment]
@gsemino Can you review this again?  I made the changes suggested in several issues.

**Comment by gsemino** [comment]
Reviewing 34-36, will post comments here

**Comment by gsemino** [comment]
@jettlin , all the changes look good, changes should be merged.  tested: uploading, adding a video to a post, domain restriction, domain restriction description, views, delete with confirmations, delete graying out, checked for showing old videos, user names in dropdown and only showing videos for particular user when chosen, uploaded tab font for top description area, copy function works

**Comment by jettlin** [comment]
From Glen:

> @Josh Ettlin, changes look good, ready to merge whenever you have a chance

Merging and deploying plugin

**Comment by gsemino** [comment]
@jettlin , I think we are good on these issues, are you able to close?

**Pull request merged**
